# Generated by Django 6.0 on 2026-01-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_locker_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locker',
            unique_together={('location', 'locker_number')},
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='location_uploads/'),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='locker',
            name='locker_number',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='locker',
            name='image',
        ),
    ]
