# Generated by Django 6.0 on 2026-02-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_is_seller_location_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locker',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='locker',
            name='locker_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
