# Generated by Django 6.0 on 2026-02-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_locker_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='unlock_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
